const prodNames = [
  {id : "1", name :"5 Centimeters Per Second"},
{id : "2", name :"A Certain Scientific Railgun T"},
{id : "3", name :"ACCA_ 13-ku Kansatsu-ka"},
{id : "4", name :"Aion"},
{id : "5", name :"Ajin"},
{id : "6", name :"Akagami no Shirayukihime"},
{id : "7", name :"Akame ga KILL! "},
{id : "8", name :"Akatsuki"},
{id : "9", name :"Akira "},
{id : "10", name :"Amnesia "},
{id : "11", name :"Anime"},
{id : "12", name :"Are You Alice_"},
{id : "13", name :"Attack on Titan"},
{id : "14", name :"Attack on Titan_ Levi"},
{id : "15", name :"Avatar"},
{id : "16", name :"Berserk "},
{id : "17", name :"Bleach "},
{id : "18", name :"Boruto"},
{id : "19", name :"Butterfly Dream"},
{id : "20", name :"Castle In The Sky "},
{id : "21", name :"Code Geass"},
{id : "22", name :"Cowboy Bebop "},
{id : "23", name :"D.Gray-man"},
{id : "24", name :"Dark Theater"},
{id : "25", name :"Death Note "},
{id : "26", name :"Fairy Tail"},
{id : "27", name :"Final Fantasi"},
{id : "28", name :"Future Diary"},
{id : "29", name :"Ghost In The Shell"},
{id : "30", name :"Girls With Butterflies"},
{id : "31", name :"Grave Of The Fireflies"},
{id : "32", name :"Gundam"},
{id : "33", name :"Haibane Renmei"},
{id : "34", name :"Haikyuu!!"},
{id : "35", name :"Howl_s Moving Castle "},
{id : "36", name :"Imitation and Creativity in Japanese Art"},
{id : "37", name :"Innocent Grey Haruka Shimotsuki"},
{id : "38", name :"Izette The Last Witch"},
{id : "39", name :"Jojo "},
{id : "40", name :"Jojo "},
{id : "41", name :"Kiki’s Delivery Service "},
{id : "42", name :"Lineage"},
{id : "43", name :"Megami"},
{id : "44", name :"Monster By Aoki Urasawa"},
{id : "45", name :"My Neighbor Totoro "},
{id : "46", name :"Naruto "},
{id : "47", name :"Nausicaa "},
{id : "48", name :"Ponyo "},
{id : "49", name :"Porco Rosso "},
{id : "50", name :"Princesse Mononoke "},
{id : "51", name :"Spirited Away "},
{id : "52", name :"The Castle Of Cagliostro "},
{id : "53", name :"The Secret World Of Arrietty "},
{id : "54", name :"The Wind Rises "},
{id : "55", name :"Whisper Of The Heart "},
{id : "56", name :"Your Name "},


  ]



  const apiResult = [{title:"5 Centimeters Per Second Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"A Certain Scientific Railgun T Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"ACCA_ 13-ku Kansatsu-ka Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Aion Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Ajin Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Akagami no Shirayukihime Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Akame ga KILL! Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Akame ga KILL! Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Akatsuki Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Akira Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Akira Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Akira Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Akira Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Akira Poster №5",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Akira Poster №6",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Amnesia Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Amnesia Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Anime Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Are You Alice_ Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Attack on Titan Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Attack on Titan_ Levi Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Avatar Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Berserk Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Berserk Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Bleach Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Bleach Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Bleach Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Boruto Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Butterfly Dream Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Castle In The Sky Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Castle In The Sky Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Castle In The Sky Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Castle In The Sky Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Castle In The Sky Poster №5",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Code Geass Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Cowboy Bebop Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Cowboy Bebop Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Cowboy Bebop Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"D.Gray-man Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Dark Theater Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Death Note Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Death Note Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Death Note Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Fairy Tail Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Final Fantasi Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Future Diary Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Ghost In The Shell Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Girls With Butterflies Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Grave Of The Fireflies Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Gundam Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Haibane Renmei Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Haikyuu!! Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Howl_s Moving Castle Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Howl_s Moving Castle Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Howl_s Moving Castle Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Imitation and Creativity in Japanese Art Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Innocent Grey Haruka Shimotsuki Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Izette The Last Witch Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Jojo Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Jojo poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Kiki’s Delivery Service Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Kiki’s Delivery Service Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Kiki’s Delivery Service Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Kiki’s Delivery Service Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Lineage Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Megami Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Monster By Aoki Urasawa Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"My Neighbor Totoro Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"My Neighbor Totoro Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"My Neighbor Totoro Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"My Neighbor Totoro Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"My Neighbor Totoro Poster №5",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"My Neighbor Totoro Poster №6",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"My Neighbor Totoro Poster №7",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Naruto Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Naruto Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Naruto Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Naruto Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Naruto Poster №5",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Naruto Poster №6",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Naruto Poster №7",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Naruto Poster №8",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Naruto Poster №9",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Naruto Poster №10",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Naruto Poster №11",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Nausicaa Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Nausicaa Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Nausicaa Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Nausicaa Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Nausicaa Poster №5",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Ponyo Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Ponyo Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Ponyo Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Porco Rosso Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Porco Rosso Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Porco Rosso Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Porco Rosso Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Princesse Mononoke Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Princesse Mononoke Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Spirited Away Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Spirited Away Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Spirited Away Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Spirited Away Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Spirited Away Poster №5",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Spirited Away Poster №6",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Spirited Away Poster №7",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Spirited Away Poster №8",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The Castle Of Cagliostro Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The Castle Of Cagliostro Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The Castle Of Cagliostro Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The Secret World Of Arrietty Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The Secret World Of Arrietty Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The Wind Rises Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The Wind Rises Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The Wind Rises Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Whisper Of The Heart Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Whisper Of The Heart Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Your Name Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Your Name Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Your Name Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},];
  