const prodNames = [
  {id : "1", name :"Aaron Gordon"},
  {id : "2", name :"Anthony Davis"},
  {id : "3", name :"Ben Simmons "},
  {id : "4", name :"Bradley Beal "},
  {id : "5", name :"Brooklyn Nets"},
  {id : "6", name :"D_Angelo Russell"},
  {id : "7", name :"Dame Dolla"},
  {id : "8", name :"Damian Lillard"},
  {id : "9", name :"Darius Garland"},
  {id : "10", name :"De_aaron Fox"},
  {id : "11", name :"Dejounte Murray"},
  {id : "12", name :"Demar Derozan"},
  {id : "13", name :"Derrick Rose "},
  {id : "14", name :"Devin Booker"},
  {id : "15", name :"Devonte_ Graham"},
  {id : "16", name :"Donovan Mitchell "},
  {id : "17", name :"Dwyane Wade"},
  {id : "18", name :"Giannis Antetokounmpo "},
  {id : "19", name :"Ja Morant "},
  {id : "20", name :"Jamal Murray"},
  {id : "21", name :"James Harden "},
  {id : "22", name :"Jaren Jackson"},
  {id : "23", name :"Jeremy Lin"},
  {id : "24", name :"Jimmy Butler"},
  {id : "25", name :"Julius Randle"},
  {id : "26", name :"Karl-Anthony Towns"},
  {id : "27", name :"Kawhi Leonard "},
  {id : "28", name :"Kemba Walker"},
  {id : "29", name :"Kendrick Nunn"},
  {id : "30", name :"Kevin Durant"},
  {id : "31", name :"Klay Thompson"},
  {id : "32", name :"Kobe Bryant "},
  {id : "33", name :"Kristap Porzingis"},
  {id : "34", name :"Kyle Lowry "},
  {id : "35", name :"Lebron James "},
  {id : "36", name :"Luka Doncic "},
  {id : "37", name :"Michael Jordan "},
  {id : "38", name :"Mike Conley"},
  {id : "39", name :"NBA "},
  {id : "40", name :"Pascal Siakam"},
  {id : "41", name :"Pascal"},
  {id : "42", name :"RJ Barrett"},
  {id : "43", name :"Shai-Gilgeous Alexander"},
  {id : "44", name :"Shaquille O_Neal"},
  {id : "45", name :"Steph Curry "},
  {id : "46", name :"Trae Young"},
  {id : "47", name :"Victor Oladipo"},
  {id : "48", name :"Zach Lavine "},
  {id : "49", name :"Zion Williamso"},
  {id : "50", name :"Aaron Gordon "},
  {id : "51", name :"Al Horford"},
  {id : "52", name :"Allen Iverson "},
  {id : "53", name :"Andrew Wiggins"},
  {id : "54", name :"Anthony Davis "},
  {id : "55", name :"Ben Simmons "},
  {id : "56", name :"Blake Griffi"},
  {id : "57", name :"Boston Celtics"},
  {id : "58", name :"Chris Paul"},
  {id : "59", name :"CJ Mccollum"},
  {id : "60", name :"Damian Lillard "},
  {id : "61", name :"Deandre Jordan"},
  {id : "62", name :"Demar Derozan "},
  {id : "63", name :"Giannis Antetokounmpo "},
  {id : "64", name :"Harrison Barnes"},
  {id : "65", name :"James Harden "},
  {id : "66", name :"John Wall"},
  {id : "67", name :"Kawhi Leonard "},
  {id : "68", name :"Kevin Durant "},
  {id : "69", name :"Kobe Bryant "},
  {id : "70", name :"Kyrie Irving"},
  {id : "71", name :"Lebron James "},
  {id : "72", name :"Marc Gasol"},
  {id : "73", name :"Russell Westbrook "},
  {id : "74", name :"Serge Ibaka"},
  {id : "75", name :"Tim Dunca"},
  
    

  ]



  const apiResult = [
    {title:"Aaron Gordon Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Anthony Davis Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Ben Simmons Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Ben Simmons Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Ben Simmons Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Bradley Beal Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Bradley Beal Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Brooklyn Nets Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"D_Angelo Russell Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Dame Dolla Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Damian Lillard Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Darius Garland Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"De_aaron Fox Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Dejounte Murray Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Demar Derozan Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Derrick Rose Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Derrick Rose Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Devin Booker Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Devonte_ Graham Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Donovan Mitchell Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Donovan Mitchell Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Dwyane Wade Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Giannis Antetokounmpo Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Giannis Antetokounmpo Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Giannis Antetokounmpo Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Giannis Antetokounmpo Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Ja Morant Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Ja Morant Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Jamal Murray Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"James Harden Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"James Harden Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"James Harden Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Jaren Jackson Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Jeremy Lin Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Jimmy Butler Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Julius Randle Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Karl-Anthony Towns Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Kawhi Leonard Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Kawhi Leonard Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Kawhi Leonard Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Kemba Walker Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Kendrick Nunn Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Kevin Durant Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Klay Thompson Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Kobe Bryant Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Kobe Bryant Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Kobe Bryant Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Kristap Porzingis Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Kyle Lowry Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Kyle Lowry Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Lebron James Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Lebron James Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Lebron James Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Lebron James Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Lebron James Poster №5",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Lebron James Poster №6",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Lebron James Poster №7",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Luka Doncic Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Luka Doncic Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Luka Doncic Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Luka Doncic Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Luka Doncic Poster №5",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Michael Jordan Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Michael Jordan Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Mike Conley Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"NBA Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"NBA Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Pascal Siakam Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Pascal Siakam",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"RJ Barrett Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Shai-Gilgeous Alexander Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Shaquille O_Neal Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Steph Curry Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Steph Curry Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Steph Curry Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Steph Curry Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Steph Curry Poster №5",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Trae Young Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Victor Oladipo Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Zach Lavine Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Zach Lavine Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Zach Lavine Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Zion Williamson Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Aaron Gordon Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Al Horford Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Allen Iverson Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Allen Iverson Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Allen Iverson Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Allen Iverson Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Allen Iverson Poster №5",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Andrew Wiggins Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Anthony Davis Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Ben Simmons Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Blake Griffin Poste",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Boston Celtics Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Chris Paul Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"CJ Mccollum Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Damian Lillard Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Damian Lillard Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Damian Lillard Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Deandre Jordan Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Demar Derozan Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Demar Derozan Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Giannis Antetokounmpo Poster №5",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Harrison Barnes Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"James Harden Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"John Wall Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Kawhi Leonard Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Kevin Durant Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Kevin Durant Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Kevin Durant Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Kobe Bryant Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Kobe Bryant Poster №5",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Kyrie Irving Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Lebron James Poster №8",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Marc Gasol Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Russell Westbrook Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Russell Westbrook Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Serge Ibaka Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
{title:"Tim Duncan Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},];