const prodNames = [
{id : 1, name :"Aguero"},
{id : 2, name :"Alexander-Arnold"},
{id : 3, name :"Aubameyang"},
{id : 4, name :"Becker Alisson"},
{id : 5, name :"Benzema"},
{id : 6, name :"Bruno Fernandes "},
{id : 7, name :"Buffon"},
{id : 8, name :"Cavani"},
{id : 9, name :"Cristiano Ronaldo "},
{id : 10, name :"Diogo Jota"},
{id : 11, name :"Dybala"},
{id : 12, name :"Erling Haaland "},
{id : 13, name :"Frank Lampard"},
{id : 14, name :"Gareth Bale "},
{id : 15, name :"Hugo Lloris"},
{id : 16, name :"Ibrahimovic"},
{id : 17, name :"Jamal Musiala"},
{id : 18, name :"James Rodrigues"},
{id : 19, name :"Jamie Vardy"},
{id : 20, name :"Kevin De Bruyne"},
{id : 21, name :"Kyle Walker"},
{id : 22, name :"Lallana"},
{id : 23, name :"Maradonna"},
{id : 24, name :"Mbappe "},
{id : 25, name :"Messi "},
{id : 26, name :"Neymar "},
{id : 27, name :"Neymar"},
{id : 28, name :"Pogba "},
{id : 29, name :"Roberto Firmino"},
{id : 30, name :"Ronaldinho "},
{id : 31, name :"Salah"},
{id : 32, name :"Scott Mctominay"},
{id : 33, name :"Serge Gnabry"},
{id : 34, name :"Sergio Ramos"},
{id : 35, name :"Takumi Minamino"},
{id : 36, name :"Thiago Alcantara"},
{id : 37, name :"Timo Werner"},
{id : 38, name :"Van Dijk "},
{id : 39, name :"Wijnaldum"},
{id : 40, name :"Zlatan Ibrahimovi"},
{id : "41", name :"AC Milan"},
{id : "42", name :"Alvaro Morata"},
{id : "43", name :"Alvaro Negredo"},
{id : "44", name :"Barcelona "},
{id : "45", name :"Bayern Munich"},
{id : "46", name :"Brazil"},
{id : "47", name :"Buffon "},
{id : "48", name :"Cenk Tosun"},
{id : "49", name :"Chelsea"},
{id : "50", name :"Coutinho "},
{id : "51", name :"Cristiano Ronaldo "},
{id : "52", name :"Dybala "},
{id : "53", name :"EL Clasico "},
{id : "54", name :"England"},
{id : "55", name :"Fabricio"},
{id : "56", name :"Frank Lampard "},
{id : "57", name :"Gareth Bale "},
{id : "58", name :"Germany"},
{id : "59", name :"Germany VS Poland"},
{id : "60", name :"Harry Kane "},
{id : "61", name :"Hazard "},
{id : "62", name :"Inter Milan"},
{id : "63", name :"Isco "},
{id : "64", name :"Liverpool "},
{id : "65", name :"Lozano"},
{id : "66", name :"Luka Modric"},
{id : "67", name :"Lukaku"},
{id : "68", name :"Luke Shaw"},
{id : "69", name :"Manchester United "},
{id : "70", name :"Maradona "},
{id : "71", name :"Marcelo"},
{id : "72", name :"Marcos Alonso"},
{id : "73", name :"Mauro Icardi"},
{id : "74", name :"Mbappe "},
{id : "75", name :"Messi "},
{id : "76", name :"Napoli"},
{id : "77", name :"Neymar "},
{id : "78", name :"Olivier Giroud"},
{id : "79", name :"Ozil"},
{id : "80", name :"Pjanic"},
{id : "81", name :"Pogba "},
{id : "82", name :"Real Madrid "},
{id : "83", name :"Steven Gerrard"},
{id : "84", name :"Thierry Henry"},
{id : "85", name :"Toni Kroos"},
{id : "86", name :"Wayne Roone"},
  ]




  const apiResult = [{title:"Aguero Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Alexander-Arnold Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Aubameyang Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Becker Alisson Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Benzema Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Bruno Fernandes Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Bruno Fernandes Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Buffon Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Cavani Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Cristiano Ronaldo Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Cristiano Ronaldo Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Cristiano Ronaldo Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Cristiano Ronaldo Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Diogo Jota Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Dybala Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Erling Haaland Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Erling Haaland Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Frank Lampard Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Gareth Bale Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Gareth Bale Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Hugo Lloris Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Ibrahimovic Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Jamal Musiala Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"James Rodrigues Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Jamie Vardy Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Kevin De Bruyne Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Kyle Walker Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Lallana Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Maradonna Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Mbappe Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Mbappe Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Mbappe Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Mbappe Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Mbappe Poster №5",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Messi Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Messi Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Messi Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Messi Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Neymar Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Neymar Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Pogba Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Roberto Firmino Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Ronaldinho Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Ronaldinho Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Ronaldinho Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Salah Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Scott Mctominay Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Serge Gnabry Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Sergio Ramos Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Takumi Minamino Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Thiago Alcantara Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Timo Werner Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Van Dijk Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Van Dijk Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Wijnaldum Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Zlatan Ibrahimovic Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"AC Milan Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Alvaro Morata Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Alvaro Negredo Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Barcelona Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Barcelona Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Bayern Munich Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Brazil Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Buffon Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Cenk Tosun Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Chelsea Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Coutinho Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Coutinho Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Cristiano Ronaldo Poster №5",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Dybala Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"EL Clasico Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"EL Clasico Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"EL Clasico Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"EL Clasico Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"England Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Fabricio Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Frank Lampard Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Gareth Bale Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Gareth Bale Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Germany Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Germany VS Poland Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Harry Kane Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Harry Kane Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Hazard Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Hazard Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Inter Milan Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Isco Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Isco Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Liverpool Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Liverpool Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Liverpool Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Lozano Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Luka Modric Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Lukaku Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Luke Shaw Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Manchester United Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Manchester United Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Manchester United Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Maradona Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Marcelo Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Marcos Alonso Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Mauro Icardi Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Mbappe Poster №6",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Mbappe Poster №7",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Messi Poster №5",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Messi Poster №6",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Messi Poster №7",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Messi Poster №8",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Napoli Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Neymar Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Olivier Giroud Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Ozil Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Pjanic Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Pogba Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Real Madrid Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Real Madrid Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Steven Gerrard Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Thierry Henry Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Toni Kroos Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Wayne Rooney Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},];