const prodNames = [
  {id : 1, name :"12 Angry Man "},
{id : 2, name :"1917"},
{id : 3, name :"Ace Ventura "},
{id : 4, name :"Alien "},
{id : 5, name :"Amelie"},
{id : 6, name :"Annihilation "},
{id : 7, name :"Apocalypse Now "},
{id : 8, name :"Aquaman "},
{id : 9, name :"Avengers "},
{id : 10, name :"Baby Driver"},
{id : 11, name :"Back To The Future "},
{id : 12, name :"Batman "},
{id : 13, name :"Batman VS Superman "},
{id : 14, name :"Birds Of Prey "},
{id : 15, name :"Black Phanter "},
{id : 16, name :"Blade Runner "},
{id : 17, name :"Bohemian Rhapsody "},
{id : 18, name :"Borat"},
{id : 19, name :"Breakfast At Tiffany_s "},
{id : 20, name :"Bronson"},
{id : 21, name :"Captain America "},
{id : 22, name :"Captain Marvel "},
{id : 23, name :"Casablanca "},
{id : 24, name :"Casino "},
{id : 25, name :"Clerks "},
{id : 26, name :"Cruella "},
{id : 27, name :"Dead Man"},
{id : 28, name :"Deadpool "},
{id : 29, name :"Death Proof "},
{id : 30, name :"Dirty Dancing "},
{id : 31, name :"Django "},
{id : 32, name :"Doctor Sleep "},
{id : 33, name :"Dracula "},
{id : 34, name :"Drive "},
{id : 35, name :"Escape From New York "},
{id : 36, name :"Fight Club "},
{id : 37, name :"Ford VS Ferrari "},
{id : 38, name :"Forrest Gump "},
{id : 39, name :"Garfield"},
{id : 40, name :"Ghostbusters "},
{id : 41, name :"Gladiator "},
{id : 42, name :"Glass"},
{id : 43, name :"Godzilla"},
{id : 44, name :"Godzilla VS Kong "},
{id : 45, name :"Goodfellas"},
{id : 46, name :"Great Getsby "},
{id : 47, name :"Green Book"},
{id : 48, name :"Green Mile"},
{id : 49, name :"Green Street Hooligans "},
{id : 50, name :"Gremlins "},
{id : 51, name :"Guardians Of The Galaxy "},
{id : 52, name :"Hachi"},
{id : 53, name :"Harry Potter "},
{id : 54, name :"Hobbit "},
{id : 55, name :"Home Alone "},
{id : 56, name :"Hulk "},
{id : 57, name :"Human Traffic "},
{id : 58, name :"Inception"},
{id : 59, name :"Indiana Jones "},
{id : 60, name :"Interstellar "},
{id : 61, name :"Into Darkness"},
{id : 62, name :"Iron Man "},
{id : 63, name :"It"},
{id : 64, name :"It_s A Wonderfull Life"},
{id : 65, name :"Jaws"},
{id : 66, name :"Joker "},
{id : 67, name :"Jurassic Park "},
{id : 68, name :"Justice League "},
{id : 69, name :"Kill Bill "},
{id : 70, name :"King Kong "},
{id : 71, name :"La La Land "},
{id : 72, name :"Le Mans"},
{id : 73, name :"Le Professionnel"},
{id : 74, name :"Leon "},
{id : 75, name :"Little Miss Sunshine "},
{id : 76, name :"Little Women "},
{id : 77, name :"Logan "},
{id : 78, name :"Loki "},
{id : 79, name :"Mad Max "},
{id : 80, name :"Man Of Steel "},
{id : 81, name :"Marvel Studios"},
{id : 82, name :"Men In Black"},
{id : 83, name :"Montage Of Heck"},
{id : 84, name :"Mortal Kombat "},
{id : 85, name :"Mr.Nobody"},
{id : 86, name :"My Fair Lady "},
{id : 87, name :"Ninja Turtles "},
{id : 88, name :"Notebook"},
{id : 89, name :"Once Upon A Time In Hollywood "},
{id : 90, name :"One Day"},
{id : 91, name :"Only Lovers Left Alive "},
{id : 92, name :"Pirates Of The Caribbean "},
{id : 93, name :"Psycho "},
{id : 94, name :"Pulp Fiction "},
{id : 95, name :"Rain Man "},
{id : 96, name :"Requiem For A Dream"},
{id : 97, name :"Reservoir Dogs "},
{id : 98, name :"Robocop"},
{id : 99, name :"Rocky "},
{id : 100, name :"Rogue One "},
{id : 101, name :"Roman Holiday "},
{id : 102, name :"Scarface "},
{id : 103, name :"Seven "},
{id : 104, name :"Snatch "},
{id : 105, name :"Space Jam "},
{id : 106, name :"Spider-Man "},
{id : 107, name :"Star Wars "},
{id : 108, name :"Straight Outta Compton"},
{id : 109, name :"Stuart Little "},
{id : 110, name :"Suicide Squad "},
{id : 111, name :"Sunshine "},
{id : 112, name :"Taxi Driver "},
{id : 114, name :"Terminator "},
{id : 115, name :"The Big Lebowski "},
{id : 116, name :"The Departed "},
{id : 117, name :"The Dreamers "},
{id : 118, name :"The Fast And The Furious "},
{id : 119, name :"The Gentlemen"},
{id : 120, name :"The Godfather "},
{id : 122, name :"The Grand Budapest Hotel "},
{id : 123, name :"The Kid "},
{id : 124, name :"The Lighthouse"},
{id : 125, name :"The Lord Of The Rings "},
{id : 126, name :"The Lord Of The Rings"},
{id : 127, name :"The Majestic"},
{id : 128, name :"The Mandalorian "},
{id : 129, name :"The Martian "},
{id : 130, name :"The Mask"},
{id : 131, name :"The Matrix "},
{id : 132, name :"The Nice Guys "},
{id : 133, name :"The Shawshank Redemption "},
{id : 134, name :"The Shining "},
{id : 135, name :"The Thing "},
{id : 136, name :"The Wolf Of Wall Street"},
{id : 137, name :"Thor "},
{id : 138, name :"Titanic "},
{id : 139, name :"Vendeta "},
{id : 140, name :"Venom "},
{id : 141, name :"Wandavision "},
{id : 142, name :"Warrior "},
{id : 143, name :"Watchmen "},
{id : 144, name :"Wonder Woman "},
{id : 145, name :"X-Men "},

  ]



  const apiResult = [

    {title:"12 Angry Man Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"12 Angry Man Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"1917 Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Ace Ventura Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Ace Ventura Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Alien Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Alien Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Amelie Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Annihilation Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Aquaman Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Avengers Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Apocalypse Now Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Avengers Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Baby Driver Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Back To The Future Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Back To The Future Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Batman Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Batman Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Batman VS Superman Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Birds Of Prey Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Black Phanter Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Blade Runner Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Blade Runner Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Bohemian Rhapsody Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Borat Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Breakfast At Tiffany_s Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Bronson Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Captain America Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Captain America Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Captain Marvel Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Casablanca Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Casablanca Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Casino Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Clerks Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Cruella Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Dead Man Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Deadpool Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Deadpool Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Death Proof Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Dirty Dancing Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Django Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Doctor Sleep Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Dracula Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Drive Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Escape From New York Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Fight Club Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Fight Club Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Ford VS Ferrari Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Forrest Gump Poster_",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Garfield Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Ghostbusters Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Gladiator Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Glass Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Godzilla Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Godzilla VS Kong Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Goodfellas Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Great Getsby Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Green Book Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Green Mile Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Green Street Hooligans Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Gremlins Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Guardians Of The Galaxy Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Guardians Of The Galaxy Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Hachi Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Harry Potter Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Harry Potter Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Hobbit Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Home Alone Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Hulk Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Human Traffic Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Inception Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Indiana Jones Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Indiana Jones Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Interstellar Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Interstellar Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Into Darkness Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Iron Man Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"IT Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"It_s A Wonderfull Life Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Jaws Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Joker Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Jurassic Park Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Justice League Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Kill Bill Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Kill Bill Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"King Kong Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"La La Land Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Le Mans Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Le Professionnel Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Leon Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Little Miss Sunshine Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Little Women Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Logan Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Loki Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Mad Max Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Man Of Steel Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Marvel Studios Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Men In Black Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Montage Of Heck Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Mortal Kombat Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Mr.Nobody Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"My Fair Lady Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Ninja Turtles Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Notebook Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Once Upon A Time In Hollywood Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"One Day Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Only Lovers Left Alive Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Pirates Of The Caribbean Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Psycho Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Pulp Fiction Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Pulp Fiction Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Rain Man Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Requiem For A Dream Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Reservoir Dogs Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Reservoir Dogs Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Robocop Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Rocky Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Rocky Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Rogue One Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Roman Holiday Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Scarface Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Scarface Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Seven Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Snatch Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Snatch Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Space Jam Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Space Jam Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Spider-Man Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Spider-Man Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Star Wars Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Star Wars Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Star Wars Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Straight Outta Compton Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Stuart Little Poster_",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Suicide Squad Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Sunshine Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Taxi Driver Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Terminator Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Terminator Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"The Big Lebowski Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"The Departed Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"The Dreamers Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"The Fast And The Furious Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"The Gentlemen Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"The Godfather Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"The Godfather Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"The Grand Budapest Hotel Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"The Grand Budapest Hotel Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"The Kid Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"The Lighthouse Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"The Lord Of The Rings Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"The Lord Of The Rings Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"The Lord Of The Rings Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"The Lord Of The Rings Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"The Majestic Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"The Mandalorian Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"The Mandalorian Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"The Mandalorian Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"The Martian Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"The Martian Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"The Mask Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"The Matrix Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"The Nice Guys Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"The Shawshank Redemption Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"The Shawshank Redemption Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"The Shining Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"The Shining Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"The Shining Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"The Thing Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"The Thing Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"The Wolf Of Wall Street Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Thor Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Thor Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Thor Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Titanic Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Titanic Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Vendeta Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Vendeta Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Venom Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Venom Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Wandavision Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Warrior Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Watchmen Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Watchmen Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Wonder Woman Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"Wonder Woman Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"X-Men Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"X-Men Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
    {title:"X-Men Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},

];