const prodNames = [
  {id : "1", name :"3X5"},
  {id : "2", name :"4X6"},
  {id : "3", name :"5X7"},
  {id : "4", name :"6X8"},
  {id : "5", name :"8X8"},
  {id : "6", name :"2X3"},
  {id : "7", name :"3X4"},
  {id : "8", name :"4X5"},
  {id : "9", name :"5X6"},
  {id : "10", name :"6X7"},
  {id : "11", name :"7X8"},
  {id : "12", name :"1X3"},
  {id : "13", name :"2X6"},
  {id : "14", name :"3X9"},
  {id : "15", name :"1X2"},
  {id : "16", name :"2X4"},
  {id : "17", name :"4X8"},
  {id : "18", name :"1X1"},
  {id : "19", name :"2X2"},
  {id : "20", name :"4X4"},
  {id : "21", name :"5X5"},
  {id : "22", name :"6X6"},
  {id : "23", name :"7X7"},
  {id : "24", name :"3X3"},
  {id : "25", name :"მხოლოდ ტილო"},
  {id : "26", name :"ფოტოქაღალდი + პასპარტუ + ჩარჩო"},
  {id : "27", name :"ფოტოქაღალდი + ჩარჩო"},

  
  ]



  const apiResult = [

    {title:"3X5 20X36 Multicollage №3",description: "მასალა: ფოტოქაღალდი + ჩარჩო",output: "ფასი: 19"},
    {title:"4X6 26X38 Multicollage №3",description: "მასალა: ფოტოქაღალდი + ჩარჩო",output: "ფასი: 26"},
    {title:"5X7 32X44 Multicollage №3",description: "მასალა: ფოტოქაღალდი + ჩარჩო",output: "ფასი: 34"},
    {title:"6X8 38X50 Multicollage №3",description: "მასალა: ფოტოქაღალდი + ჩარჩო",output: "ფასი: 43"},
    {title:"3X5 20X32 Multicollage №2",description: "მასალა: ფოტოქაღალდი + პასპარტუ + ჩარჩო",output: "ფასი: 29"},
    {title:"4X6 26X38 Multicollage №2",description: "მასალა: ფოტოქაღალდი + პასპარტუ + ჩარჩო",output: "ფასი: 38"},
    {title:"5X7 32X44 Multicollage №2",description: "მასალა: ფოტოქაღალდი + პასპარტუ + ჩარჩო",output: "ფასი: 49"},
    {title:"6X8 38X50 Multicollage №2",description: "მასალა: ფოტოქაღალდი + პასპარტუ + ჩარჩო",output: "ფასი: 73"},
    {title:"3X5 20X32  Multicollage №1",description: "მასალა: მხოლოდ ტილო",output: "ფასი: 20"},
    {title:"4X6 26X38  Multicollage №1",description: "მასალა: მხოლოდ ტილო",output: "ფასი: 25"},
    {title:"5X7 32X44  Multicollage №1",description: "მასალა: მხოლოდ ტილო",output: "ფასი: 30"},
    {title:"6X8 38X50  Multicollage №1",description: "მასალა: მხოლოდ ტილო",output: "ფასი: 36"},
    {title:"2X3 14X20 Multicollage №3",description: "მასალა: ფოტოქაღალდი + ჩარჩო",output: "ფასი: 12"},
    {title:"3X4 20X26 Multicollage №3",description: "მასალა: ფოტოქაღალდი + ჩარჩო",output: "ფასი: 17"},
    {title:"4X5 26X32 Multicollage №3",description: "მასალა: ფოტოქაღალდი + ჩარჩო",output: "ფასი: 23"},
    {title:"5X6 38X32 Multicollage №3",description: "მასალა: ფოტოქაღალდი + ჩარჩო",output: "ფასი: 30"},
    {title:"6X7 44X38 Multicollage №3",description: "მასალა: ფოტოქაღალდი + ჩარჩო",output: "ფასი: 39"},
    {title:"7X8 50X44 Multicollage №3",description: "მასალა: ფოტოქაღალდი + ჩარჩო",output: "ფასი: 48"},
    {title:"3X4 20X26  Multicollage №2",description: "მასალა: ფოტოქაღალდი + პასპარტუ + ჩარჩო",output: "ფასი: 25"},
    {title:"4X5 26X32  Multicollage №2",description: "მასალა: ფოტოქაღალდი + პასპარტუ + ჩარჩო",output: "ფასი: 34"},
    {title:"5X6 32X38  Multicollage №2",description: "მასალა: ფოტოქაღალდი + პასპარტუ + ჩარჩო",output: "ფასი: 44"},
    {title:"6X7 44X48 Multicollage №2",description: "მასალა: ფოტოქაღალდი + პასპარტუ + ჩარჩო",output: "ფასი: 67"},
    {title:"7X8 50X44 Multicollage №2",description: "მასალა: ფოტოქაღალდი + პასპარტუ + ჩარჩო",output: "ფასი: 81"},
    {title:"2X3 14X20 Multicollage №1",description: "მასალა: მხოლოდ ტილო",output: "ფასი: 13"},
    {title:"3X4 20X26 Multicollage №1",description: "მასალა: მხოლოდ ტილო",output: "ფასი: 18"},
    {title:"4X5 26X32  Multicollage №1",description: "მასალა: მხოლოდ ტილო",output: "ფასი: 22"},
    {title:"5X6 32X38  Multicollage №1",description: "მასალა: მხოლოდ ტილო",output: "ფასი: 28"},
    {title:"6X7 44X50  Multicollage №1",description: "მასალა: მხოლოდ ტილო",output: "ფასი: 33"},
    {title:"7X8 50X44 Multicollage №1",description: "მასალა: მხოლოდ ტილო",output: "ფასი: 39"},
    {title:"1X3 8X20 Multicollage №3",description: "მასალა: ფოტოქაღალდი + ჩარჩო",output: "ფასი: 9"},
    {title:"2X6 14X38 Multicollage №3",description: "მასალა: ფოტოქაღალდი + ჩარჩო",output: "ფასი: 18"},
    {title:"3X9 20X56 Multicollage №3",description: "მასალა: ფოტოქაღალდი + ჩარჩო",output: "ფასი: 30"},
    {title:"1X3 8X20 Multicollage №2",description: "მასალა: ფოტოქაღალდი + პასპარტუ + ჩარჩო",output: "ფასი: 14"},
    {title:"2X6 14X38 Multicollage №2",description: "მასალა: ფოტოქაღალდი + პასპარტუ + ჩარჩო",output: "ფასი: 26"},
    {title:"3X9 20X56 Multicollage №2",description: "მასალა: ფოტოქაღალდი + პასპარტუ + ჩარჩო",output: "ფასი: 43"},
    {title:"1X3 8X20 Multicollage №1",description: "მასალა: მხოლოდ ტილო",output: "ფასი: 11"},
    {title:"2X6 14X38 Multicollage №1",description: "მასალა: მხოლოდ ტილო",output: "ფასი: 19"},
    {title:"3X9 20X56 Multicollage №1",description: "მასალა: მხოლოდ ტილო",output: "ფასი: 28"},
    {title:"1X2 8X14 Multicollage №3",description: "მასალა: ფოტოქაღალდი + ჩარჩო",output: "ფასი: 8"},
    {title:"2X4 14X26 Multicollage №3",description: "მასალა: ფოტოქაღალდი + ჩარჩო",output: "ფასი: 14"},
    {title:"4X8 26X50 Multicollage №3",description: "მასალა: ფოტოქაღალდი + ჩარჩო",output: "ფასი: 32"},
    {title:"1X2 8X14 Multicollage №2",description: "მასალა: ფოტოქაღალდი + პასპარტუ + ჩარჩო",output: "ფასი: 12"},
    {title:"2X4 14X26 Multicollage №2",description: "მასალა: ფოტოქაღალდი + პასპარტუ + ჩარჩო",output: "ფასი: 21"},
    {title:"4X8 26X50 Multicollage №2",description: "მასალა: ფოტოქაღალდი + პასპარტუ + ჩარჩო",output: "ფასი: 47"},
    {title:"1X2  8X14 Multicollage №1",description: "მასალა: მხოლოდ ტილო",output: "ფასი: 9"},
    {title:"2X4 14X26 Multicollage №1",description: "მასალა: მხოლოდ ტილო",output: "ფასი: 15"},
    {title:"4X8 26X50 Multicollage №1",description: "მასალა: მხოლოდ ტილო",output: "ფასი: 30"},
    {title:"1X1 14X14 Multicollage №3",description: "მასალა: ფოტოქაღალდი + ჩარჩო",output: "ფასი: 6"},
    {title:"2X2 20X20 Multicollage №3",description: "მასალა: ფოტოქაღალდი + ჩარჩო",output: "ფასი: 10"},
    {title:"4X4 26X26 Multicollage №3",description: "მასალა: ფოტოქაღალდი + ჩარჩო",output: "ფასი: 20"},
    {title:"5X5 32X32 Multicollage №3",description: "მასალა: ფოტოქაღალდი + ჩარჩო",output: "ფასი: 27"},
    {title:"6X6 38X38 Multicollage №3",description: "მასალა: ფოტოქაღალდი + ჩარჩო",output: "ფასი: 35"},
    {title:"7X7 44X44 Multicollage №3",description: "მასალა: ფოტოქაღალდი + ჩარჩო",output: "ფასი: 43"},
    {title:"8X8 50X50 Multicollage №3",description: "მასალა: ფოტოქაღალდი + ჩარჩო",output: "ფასი: 53"},
    {title:"2X2 14X14 Multicollage №2",description: "მასალა: ფოტოქაღალდი + პასპარტუ + ჩარჩო",output: "ფასი: 15"},
    {title:"3X3 20X20 Multicollage №2",description: "მასალა: ფოტოქაღალდი + პასპარტუ + ჩარჩო",output: "ფასი: 21"},
    {title:"4X4 26X26 Multicollage №2",description: "მასალა: ფოტოქაღალდი + პასპარტუ + ჩარჩო",output: "ფასი: 29"},
    {title:"5X5 32X32 Multicollage №2",description: "მასალა: ფოტოქაღალდი + პასპარტუ + ჩარჩო",output: "ფასი: 39"},
    {title:"6X6 38X38 Multicollage №2",description: "მასალა: ფოტოქაღალდი + პასპარტუ + ჩარჩო",output: "ფასი: 60"},
    {title:"7X7 44X44 Multicollage №2",description: "მასალა: ფოტოქაღალდი + პასპარტუ + ჩარჩო",output: "ფასი: 74"},
    {title:"8X8 50X50 Multicollage №2",description: "მასალა: ფოტოქაღალდი + პასპარტუ + ჩარჩო",output: "ფასი: 89"},
    {title:"2X2 14X14 Multicollage №1",description: "მასალა: მხოლოდ ტილო",output: "ფასი: 11"},
    {title:"3X3 20X20 Multicollage №1",description: "მასალა: მხოლოდ ტილო",output: "ფასი: 14"},
    {title:"4X4 26X26 Multicollage №1",description: "მასალა: მხოლოდ ტილო",output: "ფასი: 20"},
    {title:"5X5 32X32 Multicollage №1",description: "მასალა: მხოლოდ ტილო",output: "ფასი: 25"},
    {title:"6X6 38X38 Multicollage №1",description: "მასალა: მხოლოდ ტილო",output: "ფასი: 30"},
    {title:"7X7 44X44 Multicollage №1",description: "მასალა: მხოლოდ ტილო",output: "ფასი: 36"},
    {title:"8X8 50X50  Multicollage №1",description: "მასალა: მხოლოდ ტილო",output: "ფასი: 42"},
  ];
  