const prodNames = [
  {id : "1", name :"24 Hours Le-Mans "},
  {id : "2", name :"Acura Integra"},
  {id : "3", name :"Acura IXL"},
  {id : "4", name :"Acura NSX"},
  {id : "5", name :"Antonio Giovanazzi"},
  {id : "6", name :"Audi TT RS"},
  {id : "7", name :"BMW E36 M3"},
  {id : "8", name :"BMW M2"},
  {id : "9", name :"BMW M3"},
  {id : "10", name :"Bugatti Chiron"},
  {id : "11", name :"Carlos Sainz"},
  {id : "12", name :"Charles Leclerc "},
  {id : "13", name :"Checo Perez"},
  {id : "14", name :"Chevrolet Camaro "},
  {id : "15", name :"Civic EJ8"},
  {id : "16", name :"Daniel Ricciardo"},
  {id : "17", name :"Datsun 280Z"},
  {id : "18", name :"Datsun 1200"},
  {id : "19", name :"Esteban Ocon"},
  {id : "20", name :"F1 "},
  {id : "21", name :"Fernando Alonso"},
  {id : "22", name :"Ford F150"},
  {id : "23", name :"Ford Focus RS"},
  {id : "24", name :"Ford Mustang"},
  {id : "25", name :"Ford Mustang Shelby GT"},
  {id : "26", name :"George Russell"},
  {id : "27", name :"Honda Civic EG "},
  {id : "28", name :"Honda Civic EK 9"},
  {id : "29", name :"Honda Civic FD"},
  {id : "30", name :"Honda Civic"},
  {id : "31", name :"Honda Civic Type R"},
  {id : "32", name :"Honda CRX"},
  {id : "33", name :"Honda S2000 "},
  {id : "34", name :"Hyundai Y20"},
  {id : "35", name :"Integra DC 2"},
  {id : "36", name :"KIA Stinger GT"},
  {id : "37", name :"Kimi Raikkonen"},
  {id : "38", name :"Lance Stroll"},
  {id : "39", name :"Lancer Evo VI"},
  {id : "40", name :"Lando Norris "},
  {id : "41", name :"Lewis Hamilton "},
  {id : "42", name :"Lexus LS 400"},
  {id : "43", name :"Marc Marquez"},
  {id : "44", name :"Max Verstappen "},
  {id : "45", name :"Michael Schumacher "},
  {id : "46", name :"Mick Schumacher "},
  {id : "47", name :"MX 5 Miata"},
  {id : "48", name :"Nicholas Latifi"},
  {id : "49", name :"Nikita Mazepin"},
  {id : "50", name :"Nissan Silvia S15 Mona Lisa"},
  {id : "51", name :"Nissan Silvia S15"},
  {id : "52", name :"Nissan Skyline GTR R34 "},
  {id : "53", name :"Pierre Gasly"},
  {id : "54", name :"Porsche 911"},
  {id : "55", name :"Porsche 919"},
  {id : "56", name :"Porsche GT2 RS"},
  {id : "57", name :"Scion XB"},
  {id : "58", name :"Sebastian Vettel"},
  {id : "59", name :"Skoda Octavia"},
  {id : "60", name :"Toyota Altezza"},
  {id : "61", name :"Toyota Corolla AE"},
  {id : "62", name :"Toyota Corolla"},
  {id : "63", name :"Toyota GT86"},
  {id : "64", name :"Toyota Supra A90"},
  {id : "65", name :"Toyota Supra "},
  {id : "66", name :"Valtteri Bottas"},
  {id : "67", name :"Yuka Tsunod"},

  ]



  const apiResult = [{title:"24 Hours Le-Mans Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"24 Hours Le-Mans Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"24 Hours Le-Mans Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"24 Hours Le-Mans Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"24 Hours Le-Mans Poster №5",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"24 Hours Le-Mans Poster №6",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"24 Hours Le-Mans Poster №7",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"24 Hours Le-Mans Poster №8",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"24 Hours Le-Mans Poster №9",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"24 Hours Le-Mans Poster №10",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"24 Hours Le-Mans Poster №11",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"24 Hours Le-Mans Poster №12",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Acura Integra Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Acura IXL Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Acura NSX Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Antonio Giovanazzi Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Audi TT RS Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"BMW E36 M3 Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"BMW M2 Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"BMW M3 Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Bugatti Chiron Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Carlos Sainz Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Charles Leclerc Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Charles Leclerc Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Charles Leclerc Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Checo Perez Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Chevrolet Camaro Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Chevrolet Camaro Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Civic EJ8 Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Daniel Ricciardo Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Datsun 280Z Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Datsun 1200 Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Esteban Ocon Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"F1 Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"F1 Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"F1 Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"F1 Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"F1 Poster №5",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"F1 Poster №6",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"F1 Poster №7",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"F1 Poster №8",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"F1 Poster №9",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"F1 Poster №10",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"F1 Poster №11",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"F1 Poster №12",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"F1 Poster №13",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"F1 Poster №14",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"F1 Poster №15",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"F1 Poster №16",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"F1 Poster №17",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Fernando Alonso Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Ford F150 Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Ford Focus RS Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Ford Mustang Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Ford Mustang Shelby GT Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"George Russell Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Honda Civic EG Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Honda Civic EG Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Honda Civic EK 9 Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Honda Civic FD Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Honda Civic Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Honda Civic Type R Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Honda CRX Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Honda S2000 Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Honda S2000 Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Honda S2000 Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Hyundai Y20 Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Integra DC 2 Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"KIA Stinger GT Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Kimi Raikkonen Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Lance Stroll Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Lancer Evo VI Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Lando Norris Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Lando Norris Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Lewis Hamilton Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Lewis Hamilton Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Lewis Hamilton Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Lewis Hamilton Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Lewis Hamilton Poster №5",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Lewis Hamilton Poster №6",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Lewis Hamilton Poster №7",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Lexus LS 400 Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Marc Marquez Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Max Verstappen Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Max Verstappen Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Max Verstappen Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Michael Schumacher Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Michael Schumacher Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Michael Schumacher Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Michael Schumacher Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Michael Schumacher Poster №5",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Michael Schumacher Poster №6",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Michael Schumacher Poster №7",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Michael Schumacher Poster №8",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Michael Schumacher Poster №9",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Mick Schumacher Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Mick Schumacher Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"MX 5 Miata Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Nicholas Latifi Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Nikita Mazepin Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Nissan Silvia S15 Mona Lisa Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Nissan Silvia S15 Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Nissan Skyline GTR R34 Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Nissan Skyline GTR R34 Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Pierre Gasly Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Porsche 911 Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Porsche 919 Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Porsche GT2 RS Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Scion XB Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Sebastian Vettel Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Skoda Octavia Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Toyota Altezza Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Toyota Corolla AE Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Toyota Corolla Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Toyota GT86 Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Toyota Supra A90 Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Toyota Supra Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Toyota Supra Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Valtteri Bottas Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Yuka Tsunoda Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},];
  