const prodNames = [
  {id : 1, name :"BoJack Horseman "},
  {id : 2, name :"Breaking Bad "},
  {id : 3, name :"Californiacation "},
  {id : 4, name :"Dark "},
  {id : 5, name :"Disenchantment "},
  {id : 6, name :"Doctor House "},
  {id : 7, name :"Doctor Who "},
  {id : 8, name :"Friends "},
  {id : 9, name :"Game Of Thrones "},
  {id : 10, name :"I Want To Believe"},
  {id : 11, name :"Lovecraft Country"},
  {id : 12, name :"Lucifer "},
  {id : 13, name :"Maniac "},
  {id : 14, name :"MrRobot "},
  {id : 15, name :"Peaky Blinders "},
  {id : 16, name :"Queen_s Gambit"},
  {id : 17, name :"Rick And Morty "},
  {id : 18, name :"Sex And The City "},
  {id : 19, name :"South Park"},
  {id : 20, name :"Stranger Things "},
  {id : 21, name :"Supernatural "},
  {id : 22, name :"Teen Wolf "},
  {id : 23, name :"The Big Bang Theory "},
  {id : 24, name :"The Boys "},
  {id : 25, name :"The Simpsons "},
  {id : 26, name :"The Sopranos "},
  {id : 27, name :"The Walking Dead "},
  {id : 28, name :"The Wire"},
  {id : 29, name :"The X Files "},
  {id : 30, name :"The Young Pope "},
  {id : 31, name :"True Detective "},
  {id : 32, name :"Twin Peaks "},
  {id : 33, name :"Vampire Diaries "},
  {id : 34, name :"Vinyl"},
  {id : 35, name :"Westworld "},

  ]



  const apiResult = [{title:"BoJack Horseman Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"BoJack Horseman Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"BoJack Horseman Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"BoJack Horseman Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"BoJack Horseman Poster №5",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Breaking Bad Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Breaking Bad Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Breaking Bad Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Breaking Bad Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Breaking Bad Poster №5",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Breaking Bad Poster №6",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Breaking Bad Poster №7",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Californiacation Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Californiacation Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Californiacation Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Californiacation Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Californiacation Poster №5",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Californiacation Poster №6",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Californiacation Poster №7",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Dark Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Dark Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Disenchantment Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Disenchantment Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Disenchantment Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Doctor House Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Doctor House Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Doctor House Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Doctor House Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Doctor Who Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Doctor Who Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Doctor Who Poster №3(1)",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Doctor Who Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Doctor Who Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Doctor Who Poster №5",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Doctor Who Poster №6",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Doctor Who Poster №7",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Doctor Who Poster №8",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Doctor Who Poster №9",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Doctor Who Poster №10",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Doctor Who Poster №11",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Doctor Who Poster №12",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Doctor Who Poster №13",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Doctor Who Poster №14",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Friends Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Friends Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Friends Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Game Of Thrones Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Game Of Thrones Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Game Of Thrones Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Game Of Thrones Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Game Of Thrones Poster №5",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Game Of Thrones Poster №6",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Game Of Thrones Poster №7",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"I Want To Believe Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Lovecraft Country Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Lucifer Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Lucifer Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Lucifer Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Lucifer Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Maniac Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Maniac Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Maniac Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Mr.Robot Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Mr.Robot Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Mr.Robot Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Mr.Robot Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Mr.Robot Poster №5",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Mr.Robot Poster №6",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Peaky Blinders Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Peaky Blinders Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Peaky Blinders Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Peaky Blinders Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Peaky Blinders Poster №5",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Peaky Blinders Poster №6",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Peaky Blinders Poster №7",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Peaky Blinders Poster №8",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Peaky Blinders Poster №9",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Peaky Blinders Poster №10",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Queen_s Gambit Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Rick And Morty Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Rick And Morty Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Rick And Morty Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Rick And Morty Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Rick And Morty Poster №5",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Rick And Morty Poster №6",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Sex And The City Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Sex And The City Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Sex And The City Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Sex And The City Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"South Park Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Stranger Things Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Stranger Things Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Stranger Things Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Stranger Things Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Stranger Things Poster №5",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Stranger Things Poster №6",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Stranger Things Poster №7",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Stranger Things Poster №8",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Supernatural Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Supernatural Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Supernatural Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Supernatural Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Supernatural Poster №5",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Supernatural Poster №6",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Teen Wolf Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Teen Wolf Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Teen Wolf Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Teen Wolf Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The Big Bang Theory Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The Big Bang Theory Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The Big Bang Theory Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The Boys Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The Boys Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The Boys Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The Simpsons Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The Simpsons Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The Simpsons Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The Simpsons Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The Simpsons Poster №5",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The Simpsons Poster №6",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The Sopranos Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The Sopranos Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The Sopranos Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The Sopranos Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The Sopranos Poster №5",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The Sopranos Poster №6",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The Sopranos Poster №7",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The Walking Dead Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The Walking Dead Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The Walking Dead Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The Walking Dead Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The Walking Dead Poster №5",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The Walking Dead Poster №6",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The Walking Dead Poster №7",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The Walking Dead Poster №8",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The Walking Dead Poster №9",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The Wire Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The X Files Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The X Files Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The X Files Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The X Files Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The X Files Poster №5",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The X Files Poster №6",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The Young Pope Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The Young Pope Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The Young Pope Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The Young Pope Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"The Young Pope Poster №5",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"True Detective Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"True Detective Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"True Detective Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"True Detective Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"True Detective Poster №5",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"True Detective Poster №6",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"True Detective Poster №7",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"True Detective Poster №8",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"True Detective Poster №9",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"True Detective Poster №10",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"True Detective Poster №11",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Twin Peaks Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Twin Peaks Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Twin Peaks Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Twin Peaks Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Twin Peaks Poster №5",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Twin Peaks Poster №6",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Twin Peaks Poster №7",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Twin Peaks Poster №8",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Twin Peaks Poster №9",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Vampire Diaries Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Vampire Diaries Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Vampire Diaries Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Vinyl Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Westworld Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Westworld Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Westworld Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},];
  