const prodNames = [
  {id : "1", name :"Alistair Overeem "},
  {id : "2", name :"Amanda Nunes "},
  {id : "3", name :"Anderson Silva"},
  {id : "4", name :"Brock Lesnar"},
  {id : "5", name :"Conor Mcgregor "},
  {id : "6", name :"Dan Henderson"},
  {id : "7", name :"Daniel Cormier "},
  {id : "8", name :"Demetrious Johnson"},
  {id : "9", name :"Henry Cejudo"},
  {id : "10", name :"Israel Adesanya "},
  {id : "11", name :"Jon Jones "},
  {id : "12", name :"Jose Aldo "},
  {id : "13", name :"Kamaru Usman"},
  {id : "14", name :"Khabib Nurmagomedov "},
  {id : "15", name :"Max Holloway"},
  {id : "16", name :"Michael Bisping"},
  {id : "17", name :"Nate Diaz "},
  {id : "18", name :"Randy Couture"},
  {id : "19", name :"Ronda Rousey "},
  {id : "20", name :"Royce Gracie"},
  {id : "21", name :"Stipe Miocic "},
  {id : "22", name :"UFC "},

  ]



  const apiResult = [{title:"Alistair Overeem Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Alistair Overeem Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Amanda Nunes Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Amanda Nunes Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Anderson Silva Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Brock Lesnar Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Conor Mcgregor Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Conor Mcgregor Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Conor Mcgregor Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Dan Henderson Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Daniel Cormier Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Daniel Cormier Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Demetrious Johnson Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Henry Cejudo Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Israel Adesanya Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Israel Adesanya Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Jon Jones Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Jon Jones Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Jon Jones Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Jose Aldo Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Jose Aldo Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Kamaru Usman Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Khabib Nurmagomedov Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Khabib Nurmagomedov Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Khabib Nurmagomedov Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Max Holloway Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Michael Bisping Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Nate Diaz Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Nate Diaz Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Nate Diaz Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Nate Diaz Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Randy Couture Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Ronda Rousey Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Ronda Rousey Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Ronda Rousey Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Ronda Rousey Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Royce Gracie Poster",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Stipe Miocic Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Stipe Miocic Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Stipe Miocic Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"Stipe Miocic Poster №4",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"UFC Poster №1",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"UFC Poster №2",description: "ზომა≈ A3+",output: "ფასი: 6.50"},
  {title:"UFC Poster №3",description: "ზომა≈ A3+",output: "ფასი: 6.50"},];
  