const prodNames = [
  {id : "1", name :"Assassin_s Creed "},
  {id : "2", name :"Bioshock "},
  {id : "3", name :"COD "},
  {id : "4", name :"Cyberpunk "},
  {id : "5", name :"CyberPunk "},
  {id : "6", name :"Fortnite "},
  {id : "7", name :"Forza Horizon"},
  {id : "8", name :"GTA "},
  {id : "9", name :"LOL "},
  {id : "10", name :"Mafia"},
  {id : "11", name :"Mario"},
  {id : "12", name :"Mass Effect "},
  {id : "13", name :"Mortal Kombat "},
  {id : "14", name :"PUBG "},
  {id : "15", name :"Red Dead Redemption "},
  {id : "16", name :"The Legend Of Zelda"},
  {id : "17", name :"Tomb Raide"},
  ]



  const apiResult = [
    {title:"Assassin_s Creed Poster №1",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"Assassin_s Creed Poster №2",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"Assassin_s Creed Poster №3",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"Assassin_s Creed Poster №4",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"Assassin_s Creed Poster №5",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"Bioshock Poster №1",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"Bioshock Poster №2",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"Bioshock Poster №3",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"COD Poster №1",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"COD Poster №2",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"COD Poster №3",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"Cyberpunk Poster №1",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"CyberPunk Poster №2",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"Cyberpunk Poster №3",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"Cyberpunk Poster №4",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"Cyberpunk Poster №5",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"Cyberpunk Poster №6",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"Cyberpunk Poster №7",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"Cyberpunk Poster №8",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"Cyberpunk Poster №9",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"Fortnite Poster №1",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"Fortnite Poster №2",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"Fortnite Poster №3",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"Fortnite Poster №4",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"Forza Horizon Poster",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"GTA Poster №1",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"GTA Poster №2",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"GTA Poster №3",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"GTA Poster №4",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"LOL Poster №1",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"LOL Poster №2",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"LOL Poster №3",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"LOL Poster №4",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"Mafia Poster",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"Mario Poster",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"Mass Effect Poster №1",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"Mass Effect Poster №2",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"Mass Effect Poster №3",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"Mass Effect Poster №4",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"Mass Effect Poster №5",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"Mortal Kombat Poster №1",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"Mortal Kombat Poster №2",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"Mortal Kombat Poster №3",description: "ზომა≈ A3+",output: "ფასი: 7"},,
{title:"PUBG Poster №1",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"PUBG Poster №2",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"PUBG Poster №2",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"Red Dead Redemption Poster №1",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"Red Dead Redemption Poster №2",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"The Legend Of Zelda Poster",description: "ზომა≈ A3+",output: "ფასი: 7"},
{title:"Tomb Raider Poster",description: "ზომა≈ A3+",output: "ფასი: 7"},];
  